version: 2
jobs:
  build:
    docker:
      - image: docker:17.06.0-ce
    working_directory: ~/whereabouts
    steps:
      - apk add --no-cache git
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Build the image
          command: docker build -t ${DOCKER_HUB_IMAGE} .
      - deploy:
          name: Deploy the image to Docker Hub
          command: |
            if echo -n "${CIRCLE_TAG}" | grep -Eq ^v[0-9]+\.[0-9]+\.[0-9]+$; then
              docker tag ${DOCKER_HUB_IMAGE} ${DOCKER_HUB_IMAGE}:${CIRCLE_TAG}
              docker login -e ${DOCKER_HUB_EMAIL} -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}
              docker push ${DOCKER_HUB_IMAGE}:${CIRCLE_TAG}
              docker push ${DOCKER_HUB_IMAGE}
            fi

deployment:
  workaround_for_circleci_2_0:
    tag: /.*/
