version: 2
jobs:
  build:
    docker:
      - image: docker:17.06.0-ce-rc5
    working_directory: ~/whereabouts
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image
          command: docker build -t ${DOCKER_HUB_IMAGE} .
      - deploy:
          name: Deploy the image to Docker Hub
          command: |
            if [[ "${CIRCLE_TAG}" =~ ^v.*$ ]]; then
              docker tag ${DOCKER_HUB_IMAGE} ${DOCKER_HUB_IMAGE}:${CIRCLE_TAG}
              docker login -e ${DOCKER_HUB_EMAIL} -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}
              docker push ${DOCKER_HUB_IMAGE}:${CIRCLE_TAG}
              docker push ${DOCKER_HUB_IMAGE}
            fi
